name: Docker CI

on:
  # Configure Manual Trigger
  workflow_dispatch:
    inputs:
      dockerTag:
        description: 'Docker image tag'
        required: true
        default: 'latest'
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Assign defaultValue
        run: |
          USER_INPUT=${{ github.event.inputs.dockerTag }}
          # Use user input or fall back to "latest"
          echo dockerTag=${USER_INPUT:-"latest"} >> "$GITHUB_ENV"
      
      - name: show me docker tag.
        run: echo "dockerTag:'"$dockerTag"'"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PWD }}
          
      - name: build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ vars.DOCKER_ORGANIZATION }}/${{ vars.DOCKER_IMG }}:${{env.dockerTag}}