name: Sync wiki

on:
  push:
    branches:
      - master
    paths:
      - 'wiki/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Checkout wiki
        uses: actions/checkout@v3
        with:
          repository: "${{ github.repository }}.wiki"
          path: "lichess-bot.wiki"
      - name: Sync files to wiki
        run: |
          cp -r $GITHUB_WORKSPACE/wiki/* $GITHUB_WORKSPACE/lichess-bot.wiki
          cd $GITHUB_WORKSPACE/lichess-bot.wiki
          git config --global user.email "actions@github.com"
          git config --global user.name "Wiki sync"
          git add .
          git commit -m "Update wiki"
          git push --force
