name: Sync wiki

on:
  push:
    branches:
      - master
    paths:
      - 'wiki/**'
      - 'README.md'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Checkout wiki
        uses: actions/checkout@v3
        with:
          repository: "${{ github.repository }}.wiki"
          path: "lichess-bot.wiki"
      - name: Set wiki path
        uses: dorny/paths-filter@v2
        id: wiki
        with:
          filters: |
            src:
              - 'wiki/**'
      - name: Set wiki/Home.md path
        uses: dorny/paths-filter@v2
        id: home
        with:
          filters: |
            src:
              - 'wiki/Home.md'
      - name: Set README.md path
        uses: dorny/paths-filter@v2
        id: readme
        with:
          filters: |
            src:
              - 'README.md'
      - name: Prevent Conflicts
        if: |
          steps.readme.outputs.src == 'true' &&
          steps.readme.outputs.src == 'true'
        run: |
            echo "Error: Conflicting changes. Edit either the README.md file or the wiki/Home.md file, not both."
            exit 1
      - name: Set github bot global config
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "actions-user"
      - name: Sync README.md to wiki/Home.md
        if: steps.readme.outputs.src == 'true'
        run: |
          cp -r $GITHUB_WORKSPACE/README.md $GITHUB_WORKSPACE/wiki/Home.md
          git add wiki/Home.md
          git commit -m "Auto update wiki/Home.md"
          git push
      - name: Sync wiki/Home.md to README.md
        if: steps.home.outputs.src == 'true'
        run: |
          cp -r $GITHUB_WORKSPACE/wiki/Home.md $GITHUB_WORKSPACE/README.md
          git add README.md
          git commit -m "Auto update README.md"
          git push
      - name: Sync all files to wiki
        if: steps.wiki.outputs.src == 'true'
        run: |
          cp -r $GITHUB_WORKSPACE/wiki/* $GITHUB_WORKSPACE/lichess-bot.wiki
          cd $GITHUB_WORKSPACE/lichess-bot.wiki
          git add .
          git commit -m "Auto update wiki"
          git push
